### ISSUE TITLE
Fix fetch spikes for submaps - [merged]

### ISSUE THREAD

**Issue by nabobalis** [LM-SAL/aiapy#250]
In GitLab by @wtbarnes on Nov 1, 2021, 12:12

_Merges fix-spikes-submap -> master_

Fixes #121 

This also needs backporting to the 0.6 branch.

Ideally we need to figure out how to get !125 to work, but this fix is needed in the meantime.

**Comment by nabobalis** [comment]
approved this merge request

**Comment by nabobalis** [comment]
In GitLab by @codecov on Nov 1, 2021, 12:21

# [Codecov](https://codecov.io/gl/LMSAL_HUB:aia_hub/aiapy/pull/126?src=pr&el=h1&utm_medium=referral&utm_source=gitlab&utm_content=comment&utm_campaign=pr+comments&utm_term=AIA+HUB) Report
> Merging [#126](https://codecov.io/gl/LMSAL_HUB:aia_hub/aiapy/pull/126?src=pr&el=desc&utm_medium=referral&utm_source=gitlab&utm_content=comment&utm_campaign=pr+comments&utm_term=AIA+HUB) (ac5049c) into [master](https://codecov.io/gl/LMSAL_HUB:aia_hub/aiapy/commit/f1a4e2fd4e74e4327bd2f898e5c89fce2934be96?el=desc&utm_medium=referral&utm_source=gitlab&utm_content=comment&utm_campaign=pr+comments&utm_term=AIA+HUB) (f1a4e2f) will **not change** coverage.
> The diff coverage is `n/a`.

[![Impacted file tree graph](https://codecov.io/gl/LMSAL_HUB:aia_hub/aiapy/pull/126/graphs/tree.svg?width=650&height=150&src=pr&token=FV0I4R4KC1&utm_medium=referral&utm_source=gitlab&utm_content=comment&utm_campaign=pr+comments&utm_term=AIA+HUB)](https://codecov.io/gl/LMSAL_HUB:aia_hub/aiapy/pull/126?src=pr&el=tree&utm_medium=referral&utm_source=gitlab&utm_content=comment&utm_campaign=pr+comments&utm_term=AIA+HUB)

```diff
@@           Coverage Diff           @@
##           master     #126   +/-   ##
=======================================
  Coverage   97.43%   97.43%           
=======================================
  Files          16       16           
  Lines         545      545           
=======================================
  Hits          531      531           
  Misses         14       14           
```


| [Impacted Files](https://codecov.io/gl/LMSAL_HUB:aia_hub/aiapy/pull/126?src=pr&el=tree&utm_medium=referral&utm_source=gitlab&utm_content=comment&utm_campaign=pr+comments&utm_term=AIA+HUB) | Coverage Δ | |
|---|---|---|
| [aiapy/calibrate/spikes.py](https://codecov.io/gl/LMSAL_HUB:aia_hub/aiapy/pull/126/diff?src=pr&el=tree&utm_medium=referral&utm_source=gitlab&utm_content=comment&utm_campaign=pr+comments&utm_term=AIA+HUB#diff-YWlhcHkvY2FsaWJyYXRlL3NwaWtlcy5weQ==) | `98.33% <ø> (ø)` | |

------

[Continue to review full report at Codecov](https://codecov.io/gl/LMSAL_HUB:aia_hub/aiapy/pull/126?src=pr&el=continue&utm_medium=referral&utm_source=gitlab&utm_content=comment&utm_campaign=pr+comments&utm_term=AIA+HUB).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta?utm_medium=referral&utm_source=gitlab&utm_content=comment&utm_campaign=pr+comments&utm_term=AIA+HUB)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gl/LMSAL_HUB:aia_hub/aiapy/pull/126?src=pr&el=footer&utm_medium=referral&utm_source=gitlab&utm_content=comment&utm_campaign=pr+comments&utm_term=AIA+HUB). Last update [f1a4e2f...ac5049c](https://codecov.io/gl/LMSAL_HUB:aia_hub/aiapy/pull/126?src=pr&el=lastupdated&utm_medium=referral&utm_source=gitlab&utm_content=comment&utm_campaign=pr+comments&utm_term=AIA+HUB). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments?utm_medium=referral&utm_source=gitlab&utm_content=comment&utm_campaign=pr+comments&utm_term=AIA+HUB).

**Comment by nabobalis** [comment]
Doc failures are:
```
/builds/wtbarnes/aiapy/examples/download_specific_data.py failed to execute correctly: Traceback (most recent call last):
  File "/builds/wtbarnes/aiapy/examples/download_specific_data.py", line 151, in <module>
    sequence.peek()
  File "/builds/wtbarnes/aiapy/.tox/build_docs/lib/python3.8/site-packages/sunpy/map/mapsequence.py", line 456, in peek
    from sunpy.visualization.animator.mapsequenceanimator import MapSequenceAnimator  # noqa
  File "/builds/wtbarnes/aiapy/.tox/build_docs/lib/python3.8/site-packages/sunpy/visualization/animator/__init__.py", line 1, in <module>
    import mpl_animators as _animators
ModuleNotFoundError: No module named 'mpl_animators'
```

**Comment by nabobalis** [comment]
In GitLab by @wtbarnes on Nov 1, 2021, 12:44

added 9 commits

<ul><li>81b38e27...f1a4e2fd - 8 commits from branch <code>LMSAL_HUB/aia_hub:master</code></li><li>7d5e36e2 - use empty instead of zeros-like so that data.shape gives the correct shape</li></ul>

[Compare with previous version](/LMSAL_HUB/aia_hub/aiapy/-/merge_requests/126/diffs?diff_id=271068639&start_sha=81b38e279c939125c9169c1f1edb846127294b95)

**Comment by nabobalis** [comment]
In GitLab by @wtbarnes on Nov 1, 2021, 12:47

added 1 commit

<ul><li>ac5049c2 - changeloog</li></ul>

[Compare with previous version](/LMSAL_HUB/aia_hub/aiapy/-/merge_requests/126/diffs?diff_id=271069647&start_sha=7d5e36e261e90ea0b2883a5306e41f6c854c3fcf)

**Comment by nabobalis** [comment]
approved this merge request

**Comment by nabobalis** [comment]
mentioned in commit a471621005eb8fdec4e0e55c35d807ace3ac72df

**Comment by nabobalis** [comment]
picked the changes into the branch [`cherry-pick-a4716210`](/LMSAL_HUB/aia_hub/aiapy/-/tree/cherry-pick-a4716210) with commit 196b4ce1f05dacdbd01c1cae67c448c2e66027f5

**Comment by nabobalis** [comment]
mentioned in commit 196b4ce1f05dacdbd01c1cae67c448c2e66027f5

**Comment by nabobalis** [comment]
mentioned in commit b40cc55015769ff775e5f725ca5d21fddaa27f80
