### ISSUE TITLE
Channel fails to find file it needs

### ISSUE THREAD

**Issue by nabobalis** [LM-SAL/aiapy#47]
In GitLab by @nshirman on Mar 17, 2020, 16:17

`ch = Channel(94*u.angstrom)` fails to find or download the file it needs. Passing in the file manually, however, works: `ch = Channel(94*u.angstrom, instrument_file = '/Volumes/solar/ssw/sdo/aia/response/aia_V8_all_fullinst.genx')`

Entire traceback pasted below: 

```python
>>> ch = Channel(94*u.angstrom)
```

produces

```python-traceback
Files Downloaded:   0%|          | 0/1 [01:15<?, ?file/s]
Traceback (most recent call last):

  File "/Users/shirman/anaconda3/lib/python3.7/site-packages/sunpy/data/data_manager/cache.py", line 167, in _download_and_hash
    return download(url)

  File "/Users/shirman/anaconda3/lib/python3.7/site-packages/sunpy/data/data_manager/cache.py", line 162, in download
    shahash = hash_file(path)

  File "/Users/shirman/anaconda3/lib/python3.7/site-packages/sunpy/util/util.py", line 190, in hash_file
    with open(path, 'rb') as f:

FileNotFoundError: [Errno 2] No such file or directory: '/Users/shirman/sunpy/data_manager/aia_V8_all_fullinst.genx'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<ipython-input-27-d3ef68a2c28f>", line 1, in <module>
    ch = Channel(94*u.angstrom)

  File "/Users/shirman/anaconda3/lib/python3.7/site-packages/astropy/units/decorators.py", line 234, in wrapper
    return_ = wrapped_function(*func_args, **func_kwargs)

  File "/Users/shirman/aiapy/aiapy/response/channel.py", line 52, in __init__
    self._instrument_data = self._get_instrument_data(instrument_file)

  File "/Users/shirman/aiapy/aiapy/response/channel.py", line 74, in _get_instrument_data
    instrument_file = self._get_euv_instrument_file()

  File "/Users/shirman/anaconda3/lib/python3.7/site-packages/sunpy/data/data_manager/manager.py", line 73, in wrapper
    file_path = self._cache.download(urls)

  File "/Users/shirman/anaconda3/lib/python3.7/site-packages/sunpy/data/data_manager/cache.py", line 87, in download
    file_path, file_hash, url = self._download_and_hash(urls)

  File "/Users/shirman/anaconda3/lib/python3.7/site-packages/sunpy/data/data_manager/cache.py", line 169, in _download_and_hash
    warn(e, SunpyUserWarning)

TypeError: expected string or bytes-like object
```

**Comment by nabobalis** [comment]
In GitLab by @wtbarnes on Mar 17, 2020, 16:36

I just cleared out all the files I had already downloaded and the cache, created a `Channel` without passing in a file, and I'm not able to reproduce this locally

Just for the sake of clarity, what version of sunpy are you using? You can get this by typing `sunpy.version.version` at the command prompt.

**Comment by nabobalis** [comment]
In GitLab by @nshirman on Mar 17, 2020, 16:37

I'm using 1.1.1

**Comment by nabobalis** [comment]
In GitLab by @wtbarnes on Mar 17, 2020, 16:45

It seems like it doesn't like the URL we're passing in though I can't really understand how that could be different on your end as these are hardcoded. Because the download is failing, it's then not able to find the file (because it wasn't downloaded :laughing:)

**Comment by nabobalis** [comment]
In GitLab by @nshirman on Mar 17, 2020, 16:51

Hmm. I was also having problems with Fido.fetch from your sunpy tutorial - that one just times out at some point. Maybe that's related because it's also a sunpy issue? So if I did `files = Fido.fetch(q)` and printed `files` before sorting, I got the below block. If I printed `files` after sorting I just got an empty list. 
```
Out[60]: 
<parfive.results.Results object at 0xb257e5b90>
[]
Errors:
(error(filepath_partial=functools.partial(<function VSOClient.mk_filename at 0x121a105f0>, '/Users/shirman/sunpy/data/{file}', {
    'provider': 'JSOC',
    'source': 'SDO',
    'instrument': 'AIA',
    'physobs': 'intensity',
    'time': {
        'start': '20100930035136',
        'end': '20100930035137',
        'near': None
    },
    'wave': {
        'wavemin': '171',
        'wavemax': '171',
        'waveunit': 'Angstrom',
        'wavetype': 'NARROW'
    },
    'extent': {
        'x': None,
        'y': None,
        'width': '4096',
        'length': '4096',
        'type': 'FULLDISK'
    },
    'size': 66200.0,
    'extra': None,
    'info': 'AIA level 1, 4096x4096 [2.000 exposure] [100.00 percentd]',
    'datatype': None,
    'fileurl': None,
    'fileid': 'aia__lev1:171:1064893931'
}), url='http://netdrms01.nispdc.nso.edu/cgi-bin/netdrms/drms_export.cgi?series=aia__lev1;compress=rice;record=171_1064893931-1064893931', exception=ClientConnectorError(ConnectionKey(host='netdrms01.nispdc.nso.edu', port=80, is_ssl=False, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None), TimeoutError(60, "Connect call failed ('146.5.21.120', 80)"))))(error(filepath_partial=functools.partial(<function VSOClient.mk_filename at 0x121a105f0>, '/Users/shirman/sunpy/data/{file}', {
    'provider': 'JSOC',
    'source': 'SDO',
    'instrument': 'AIA',
    'physobs': 'intensity',
    'time': {
        'start': '20100929235136',
        'end': '20100929235137',
        'near': None
    },
    'wave': {
        'wavemin': '171',
        'wavemax': '171',
        'waveunit': 'Angstrom',
        'wavetype': 'NARROW'
    },
    'extent': {
        'x': None,
        'y': None,
        'width': '4096',
        'length': '4096',
        'type': 'FULLDISK'
    },
    'size': 66200.0,
    'extra': None,
    'info': 'AIA level 1, 4096x4096 [2.000 exposure] [100.00 percentd]',
    'datatype': None,
    'fileurl': None,
    'fileid': 'aia__lev1:171:1064879531'
}), url='http://netdrms01.nispdc.nso.edu/cgi-bin/netdrms/drms_export.cgi?series=aia__lev1;compress=rice;record=171_1064879531-1064879531', exception=ClientConnectorError(ConnectionKey(host='netdrms01.nispdc.nso.edu', port=80, is_ssl=False, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None), TimeoutError(60, "Connect call failed ('146.5.21.120', 80)"))))(error(filepath_partial=functools.partial(<function VSOClient.mk_filename at 0x121a105f0>, '/Users/shirman/sunpy/data/{file}', {
    'provider': 'JSOC',
    'source': 'SDO',
    'instrument': 'AIA',
    'physobs': 'intensity',
    'time': {
        'start': '20100930075136',
        'end': '20100930075137',
        'near': None
    },
    'wave': {
        'wavemin': '171',
        'wavemax': '171',
        'waveunit': 'Angstrom',
        'wavetype': 'NARROW'
    },
    'extent': {
        'x': None,
        'y': None,
        'width': '4096',
        'length': '4096',
        'type': 'FULLDISK'
    },
    'size': 66200.0,
    'extra': None,
    'info': 'AIA level 1, 4096x4096 [2.000 exposure] [100.00 percentd]',
    'datatype': None,
    'fileurl': None,
    'fileid': 'aia__lev1:171:1064908331'
}), url='http://netdrms01.nispdc.nso.edu/cgi-bin/netdrms/drms_export.cgi?series=aia__lev1;compress=rice;record=171_1064908331-1064908331', exception=ClientConnectorError(ConnectionKey(host='netdrms01.nispdc.nso.edu', port=80, is_ssl=False, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None), TimeoutError(60, "Connect call failed ('146.5.21.120', 80)"))))(error(filepath_partial=functools.partial(<function VSOClient.mk_filename at 0x121a105f0>, '/Users/shirman/sunpy/data/{file}', {
    'provider': 'JSOC',
    'source': 'SDO',
    'instrument': 'AIA',
    'physobs': 'intensity',
    'time': {
        'start': '20100930115136',
        'end': '20100930115137',
        'near': None
    },
    'wave': {
        'wavemin': '171',
        'wavemax': '171',
        'waveunit': 'Angstrom',
        'wavetype': 'NARROW'
    },
    'extent': {
        'x': None,
        'y': None,
        'width': '4096',
        'length': '4096',
        'type': 'FULLDISK'
    },
    'size': 66200.0,
    'extra': None,
    'info': 'AIA level 1, 4096x4096 [2.000 exposure] [100.00 percentd]',
    'datatype': None,
    'fileurl': None,
    'fileid': 'aia__lev1:171:1064922731'
}), url='http://netdrms01.nispdc.nso.edu/cgi-bin/netdrms/drms_export.cgi?series=aia__lev1;compress=rice;record=171_1064922731-1064922731', exception=ClientConnectorError(ConnectionKey(host='netdrms01.nispdc.nso.edu', port=80, is_ssl=False, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None), TimeoutError(60, "Connect call failed ('146.5.21.120', 80)"))))
```

**Comment by nabobalis** [comment]
In GitLab by @wtbarnes on Mar 17, 2020, 16:59

May be related. Could be that something is blocking sunpy from downloading external files.

**Comment by nabobalis** [comment]
In GitLab by @wtbarnes on Jun 16, 2020, 11:11

@nshirman Is this issue possibly related to the proxy issue that you brought up on the slack channel? Does this only happen on the LM usernet?

**Comment by nabobalis** [comment]
In GitLab by @nshirman on Jun 16, 2020, 13:11

@wtbarnes Yes, looks like it only doesn't work on the LM usernet but works otherwise - for Spyder/iPython. For Jupyter notebook if not on the LM usernet then I get a different issue, with Fido.search this time, which gives the error: 

`WARNING: SunpyUserWarning: Connection to https://sdac.virtualsolar.org/API/VSOi_rpc_literal.wsdl failed with error <urlopen error [Errno 60] Operation timed out>. Retrying with different url and port. [sunpy.net.vso.vso]`

and a long error block with `ConnectionError: No online VSO mirrors could be found.` at the bottom. So for some reason it seems like it can't connect now.

**Comment by nabobalis** [comment]
In GitLab by @wtbarnes on Jul 16, 2020, 20:22

Are you still seeing this original issue outside of the LM usernet? If not, I think we can close this.

**Comment by nabobalis** [comment]
In GitLab by @nshirman on Jul 17, 2020, 10:24

Yeah the Fido.fetch issue seems to just happen on the LM usernet.
